#!/usr/bin/env python3
"""Download the proposal typefaces (all SIL Open Font License) from Google Fonts into fonts/
and write fonts/fonts.css with local @font-face rules, so the pages work offline.

    python3 fetch-fonts.py
"""
import re, sys, urllib.request
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "fonts"; FILES = OUT / "files"; FILES.mkdir(parents=True, exist_ok=True)
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"

FAMILIES = [
    ("Fraunces", "Fraunces:opsz,wght@9..144,400..800"),
    ("Atkinson Hyperlegible Next", "Atkinson+Hyperlegible+Next:wght@200..800"),
    ("Atkinson Hyperlegible Mono", "Atkinson+Hyperlegible+Mono:wght@200..800"),
    ("Sofia Sans", "Sofia+Sans:wght@1..1000"),
    ("Sofia Sans Condensed", "Sofia+Sans+Condensed:wght@1..1000"),
    ("Sofia Sans Semi Condensed", "Sofia+Sans+Semi+Condensed:wght@1..1000"),
    ("IBM Plex Mono", "IBM+Plex+Mono:wght@400;500;700"),
    ("Literata", "Literata:opsz,wght@7..72,200..900"),
    ("Manrope", "Manrope:wght@200..800"),
    ("Commissioner", "Commissioner:wght@100..900"),
    ("Prata", "Prata"),
    ("Onest", "Onest:wght@100..900"),
    ("JetBrains Mono", "JetBrains+Mono:wght@100..800"),
    ("Nunito", "Nunito:wght@200..1000"),
]

def get(url: str, tries: int = 4) -> bytes:
    import time
    for i in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=60) as r:
                return r.read()
        except Exception as e:
            if i == tries - 1: raise
            time.sleep(1.5 * (i + 1))

css_out = ["/* Self-hosted typefaces for the Quest City Tour L&F proposals. Generated by fetch-fonts.py. All SIL OFL. */"]
total = 0
for name, spec in FAMILIES:
    try:
        css = get(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode()
    except Exception as e:
        print(f"!! {name}: {e}", file=sys.stderr); continue
    blocks = re.findall(r"(/\*\s*([\w-]+)\s*\*/\s*)?(@font-face\s*\{[^}]*\})", css)
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    n = 0
    for _, subset, block in blocks:
        m = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", block)
        if not m: continue
        url = m.group(1)
        wght = re.search(r"font-weight:\s*([^;]+);", block); style = re.search(r"font-style:\s*(\w+);", block)
        w = (wght.group(1).strip().replace(" ", "-") if wght else "400"); st = style.group(1) if style else "normal"
        fname = f"{slug}-{subset or 'latin'}-{w}-{st}.woff2"
        path = FILES / fname
        if not path.exists():
            path.write_bytes(get(url))
        total += path.stat().st_size
        block = block.replace(url, f"files/{fname}")
        css_out.append(f"/* {name} — {subset or 'latin'} */\n{block}")
        n += 1
    print(f"{name}: {n} files")
(OUT / "fonts.css").write_text("\n".join(css_out) + "\n", encoding="utf-8")
print(f"wrote fonts/fonts.css, {total/1e6:.1f} MB of woff2")
